# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SeaBattle(object):
    def setupUi2(self, SeaBattle):
        SeaBattle.setObjectName("SeaBattle")
        SeaBattle.resize(1358, 720)
        SeaBattle.setStyleSheet("background-color: rgb(40, 86, 185)")
        self.centralwidget = QtWidgets.QWidget(SeaBattle)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 30, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(620, 30, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 90, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 170, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 250, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 210, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(60, 290, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(60, 330, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(60, 370, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(60, 410, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(60, 450, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.lh1 = QtWidgets.QLabel(self.centralwidget)
        self.lh1.setGeometry(QtCore.QRect(90, 370, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lh1.setFont(font)
        self.lh1.setObjectName("lh1")
        self.lg1 = QtWidgets.QLabel(self.centralwidget)
        self.lg1.setGeometry(QtCore.QRect(90, 330, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lg1.setFont(font)
        self.lg1.setObjectName("lg1")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(90, 490, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.lc1 = QtWidgets.QLabel(self.centralwidget)
        self.lc1.setGeometry(QtCore.QRect(90, 170, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lc1.setFont(font)
        self.lc1.setObjectName("lc1")
        self.la1 = QtWidgets.QLabel(self.centralwidget)
        self.la1.setGeometry(QtCore.QRect(90, 90, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.la1.setFont(font)
        self.la1.setObjectName("la1")
        self.le1 = QtWidgets.QLabel(self.centralwidget)
        self.le1.setGeometry(QtCore.QRect(90, 250, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.le1.setFont(font)
        self.le1.setObjectName("le1")
        self.ld1 = QtWidgets.QLabel(self.centralwidget)
        self.ld1.setGeometry(QtCore.QRect(90, 210, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.ld1.setFont(font)
        self.ld1.setObjectName("ld1")
        self.lb1 = QtWidgets.QLabel(self.centralwidget)
        self.lb1.setGeometry(QtCore.QRect(90, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lb1.setFont(font)
        self.lb1.setObjectName("lb1")
        self.li1 = QtWidgets.QLabel(self.centralwidget)
        self.li1.setGeometry(QtCore.QRect(90, 410, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.li1.setFont(font)
        self.li1.setObjectName("li1")
        self.lf1 = QtWidgets.QLabel(self.centralwidget)
        self.lf1.setGeometry(QtCore.QRect(90, 290, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lf1.setFont(font)
        self.lf1.setObjectName("lf1")
        self.lj1 = QtWidgets.QLabel(self.centralwidget)
        self.lj1.setGeometry(QtCore.QRect(90, 450, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lj1.setFont(font)
        self.lj1.setObjectName("lj1")
        self.lh2 = QtWidgets.QLabel(self.centralwidget)
        self.lh2.setGeometry(QtCore.QRect(130, 370, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lh2.setFont(font)
        self.lh2.setObjectName("lh2")
        self.lg2 = QtWidgets.QLabel(self.centralwidget)
        self.lg2.setGeometry(QtCore.QRect(130, 330, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lg2.setFont(font)
        self.lg2.setObjectName("lg2")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(130, 490, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.lc2 = QtWidgets.QLabel(self.centralwidget)
        self.lc2.setGeometry(QtCore.QRect(130, 170, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lc2.setFont(font)
        self.lc2.setObjectName("lc2")
        self.la2 = QtWidgets.QLabel(self.centralwidget)
        self.la2.setGeometry(QtCore.QRect(130, 90, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.la2.setFont(font)
        self.la2.setObjectName("la2")
        self.le2 = QtWidgets.QLabel(self.centralwidget)
        self.le2.setGeometry(QtCore.QRect(130, 250, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.le2.setFont(font)
        self.le2.setObjectName("le2")
        self.ld2 = QtWidgets.QLabel(self.centralwidget)
        self.ld2.setGeometry(QtCore.QRect(130, 210, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.ld2.setFont(font)
        self.ld2.setObjectName("ld2")
        self.lb2 = QtWidgets.QLabel(self.centralwidget)
        self.lb2.setGeometry(QtCore.QRect(130, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lb2.setFont(font)
        self.lb2.setObjectName("lb2")
        self.li2 = QtWidgets.QLabel(self.centralwidget)
        self.li2.setGeometry(QtCore.QRect(130, 410, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.li2.setFont(font)
        self.li2.setObjectName("li2")
        self.lf2 = QtWidgets.QLabel(self.centralwidget)
        self.lf2.setGeometry(QtCore.QRect(130, 290, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lf2.setFont(font)
        self.lf2.setObjectName("lf2")
        self.lj2 = QtWidgets.QLabel(self.centralwidget)
        self.lj2.setGeometry(QtCore.QRect(130, 450, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lj2.setFont(font)
        self.lj2.setObjectName("lj2")
        self.lh3 = QtWidgets.QLabel(self.centralwidget)
        self.lh3.setGeometry(QtCore.QRect(170, 370, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lh3.setFont(font)
        self.lh3.setObjectName("lh3")
        self.lg3 = QtWidgets.QLabel(self.centralwidget)
        self.lg3.setGeometry(QtCore.QRect(170, 330, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lg3.setFont(font)
        self.lg3.setObjectName("lg3")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(170, 490, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.lc3 = QtWidgets.QLabel(self.centralwidget)
        self.lc3.setGeometry(QtCore.QRect(170, 170, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lc3.setFont(font)
        self.lc3.setObjectName("lc3")
        self.la3 = QtWidgets.QLabel(self.centralwidget)
        self.la3.setGeometry(QtCore.QRect(170, 90, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.la3.setFont(font)
        self.la3.setObjectName("la3")
        self.le3 = QtWidgets.QLabel(self.centralwidget)
        self.le3.setGeometry(QtCore.QRect(170, 250, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.le3.setFont(font)
        self.le3.setObjectName("le3")
        self.ld3 = QtWidgets.QLabel(self.centralwidget)
        self.ld3.setGeometry(QtCore.QRect(170, 210, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.ld3.setFont(font)
        self.ld3.setObjectName("ld3")
        self.lb3 = QtWidgets.QLabel(self.centralwidget)
        self.lb3.setGeometry(QtCore.QRect(170, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lb3.setFont(font)
        self.lb3.setObjectName("lb3")
        self.li3 = QtWidgets.QLabel(self.centralwidget)
        self.li3.setGeometry(QtCore.QRect(170, 410, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.li3.setFont(font)
        self.li3.setObjectName("li3")
        self.lf3 = QtWidgets.QLabel(self.centralwidget)
        self.lf3.setGeometry(QtCore.QRect(170, 290, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lf3.setFont(font)
        self.lf3.setObjectName("lf3")
        self.lj3 = QtWidgets.QLabel(self.centralwidget)
        self.lj3.setGeometry(QtCore.QRect(170, 450, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lj3.setFont(font)
        self.lj3.setObjectName("lj3")
        self.lh4 = QtWidgets.QLabel(self.centralwidget)
        self.lh4.setGeometry(QtCore.QRect(210, 370, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lh4.setFont(font)
        self.lh4.setObjectName("lh4")
        self.lg4 = QtWidgets.QLabel(self.centralwidget)
        self.lg4.setGeometry(QtCore.QRect(210, 330, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lg4.setFont(font)
        self.lg4.setObjectName("lg4")
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(210, 490, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.lc4 = QtWidgets.QLabel(self.centralwidget)
        self.lc4.setGeometry(QtCore.QRect(210, 170, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lc4.setFont(font)
        self.lc4.setObjectName("lc4")
        self.la4 = QtWidgets.QLabel(self.centralwidget)
        self.la4.setGeometry(QtCore.QRect(210, 90, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.la4.setFont(font)
        self.la4.setObjectName("la4")
        self.le4 = QtWidgets.QLabel(self.centralwidget)
        self.le4.setGeometry(QtCore.QRect(210, 250, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.le4.setFont(font)
        self.le4.setObjectName("le4")
        self.ld4 = QtWidgets.QLabel(self.centralwidget)
        self.ld4.setGeometry(QtCore.QRect(210, 210, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.ld4.setFont(font)
        self.ld4.setObjectName("ld4")
        self.lb4 = QtWidgets.QLabel(self.centralwidget)
        self.lb4.setGeometry(QtCore.QRect(210, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lb4.setFont(font)
        self.lb4.setObjectName("lb4")
        self.li4 = QtWidgets.QLabel(self.centralwidget)
        self.li4.setGeometry(QtCore.QRect(210, 410, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.li4.setFont(font)
        self.li4.setObjectName("li4")
        self.lf4 = QtWidgets.QLabel(self.centralwidget)
        self.lf4.setGeometry(QtCore.QRect(210, 290, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lf4.setFont(font)
        self.lf4.setObjectName("lf4")
        self.lj4 = QtWidgets.QLabel(self.centralwidget)
        self.lj4.setGeometry(QtCore.QRect(210, 450, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lj4.setFont(font)
        self.lj4.setObjectName("lj4")
        self.lh5 = QtWidgets.QLabel(self.centralwidget)
        self.lh5.setGeometry(QtCore.QRect(250, 370, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lh5.setFont(font)
        self.lh5.setObjectName("lh5")
        self.lg5 = QtWidgets.QLabel(self.centralwidget)
        self.lg5.setGeometry(QtCore.QRect(250, 330, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lg5.setFont(font)
        self.lg5.setObjectName("lg5")
        self.label_60 = QtWidgets.QLabel(self.centralwidget)
        self.label_60.setGeometry(QtCore.QRect(250, 490, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.lc5 = QtWidgets.QLabel(self.centralwidget)
        self.lc5.setGeometry(QtCore.QRect(250, 170, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lc5.setFont(font)
        self.lc5.setObjectName("lc5")
        self.la5 = QtWidgets.QLabel(self.centralwidget)
        self.la5.setGeometry(QtCore.QRect(250, 90, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.la5.setFont(font)
        self.la5.setObjectName("la5")
        self.le5 = QtWidgets.QLabel(self.centralwidget)
        self.le5.setGeometry(QtCore.QRect(250, 250, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.le5.setFont(font)
        self.le5.setObjectName("le5")
        self.ld5 = QtWidgets.QLabel(self.centralwidget)
        self.ld5.setGeometry(QtCore.QRect(250, 210, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.ld5.setFont(font)
        self.ld5.setObjectName("ld5")
        self.lb5 = QtWidgets.QLabel(self.centralwidget)
        self.lb5.setGeometry(QtCore.QRect(250, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lb5.setFont(font)
        self.lb5.setObjectName("lb5")
        self.li5 = QtWidgets.QLabel(self.centralwidget)
        self.li5.setGeometry(QtCore.QRect(250, 410, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.li5.setFont(font)
        self.li5.setObjectName("li5")
        self.lf5 = QtWidgets.QLabel(self.centralwidget)
        self.lf5.setGeometry(QtCore.QRect(250, 290, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lf5.setFont(font)
        self.lf5.setObjectName("lf5")
        self.lj5 = QtWidgets.QLabel(self.centralwidget)
        self.lj5.setGeometry(QtCore.QRect(250, 450, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lj5.setFont(font)
        self.lj5.setObjectName("lj5")
        self.lh6 = QtWidgets.QLabel(self.centralwidget)
        self.lh6.setGeometry(QtCore.QRect(290, 370, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lh6.setFont(font)
        self.lh6.setObjectName("lh6")
        self.lg6 = QtWidgets.QLabel(self.centralwidget)
        self.lg6.setGeometry(QtCore.QRect(290, 330, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lg6.setFont(font)
        self.lg6.setObjectName("lg6")
        self.label_71 = QtWidgets.QLabel(self.centralwidget)
        self.label_71.setGeometry(QtCore.QRect(290, 490, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_71.setFont(font)
        self.label_71.setObjectName("label_71")
        self.lc6 = QtWidgets.QLabel(self.centralwidget)
        self.lc6.setGeometry(QtCore.QRect(290, 170, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lc6.setFont(font)
        self.lc6.setObjectName("lc6")
        self.la6 = QtWidgets.QLabel(self.centralwidget)
        self.la6.setGeometry(QtCore.QRect(290, 90, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.la6.setFont(font)
        self.la6.setObjectName("la6")
        self.le6 = QtWidgets.QLabel(self.centralwidget)
        self.le6.setGeometry(QtCore.QRect(290, 250, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.le6.setFont(font)
        self.le6.setObjectName("le6")
        self.ld6 = QtWidgets.QLabel(self.centralwidget)
        self.ld6.setGeometry(QtCore.QRect(290, 210, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.ld6.setFont(font)
        self.ld6.setObjectName("ld6")
        self.lb6 = QtWidgets.QLabel(self.centralwidget)
        self.lb6.setGeometry(QtCore.QRect(290, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lb6.setFont(font)
        self.lb6.setObjectName("lb6")
        self.li6 = QtWidgets.QLabel(self.centralwidget)
        self.li6.setGeometry(QtCore.QRect(290, 410, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.li6.setFont(font)
        self.li6.setObjectName("li6")
        self.lf6 = QtWidgets.QLabel(self.centralwidget)
        self.lf6.setGeometry(QtCore.QRect(290, 290, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lf6.setFont(font)
        self.lf6.setObjectName("lf6")
        self.lj6 = QtWidgets.QLabel(self.centralwidget)
        self.lj6.setGeometry(QtCore.QRect(290, 450, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lj6.setFont(font)
        self.lj6.setObjectName("lj6")
        self.lh7 = QtWidgets.QLabel(self.centralwidget)
        self.lh7.setGeometry(QtCore.QRect(330, 370, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lh7.setFont(font)
        self.lh7.setObjectName("lh7")
        self.lg7 = QtWidgets.QLabel(self.centralwidget)
        self.lg7.setGeometry(QtCore.QRect(330, 330, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lg7.setFont(font)
        self.lg7.setObjectName("lg7")
        self.label_82 = QtWidgets.QLabel(self.centralwidget)
        self.label_82.setGeometry(QtCore.QRect(330, 490, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_82.setFont(font)
        self.label_82.setObjectName("label_82")
        self.lc7 = QtWidgets.QLabel(self.centralwidget)
        self.lc7.setGeometry(QtCore.QRect(330, 170, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lc7.setFont(font)
        self.lc7.setObjectName("lc7")
        self.la7 = QtWidgets.QLabel(self.centralwidget)
        self.la7.setGeometry(QtCore.QRect(330, 90, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.la7.setFont(font)
        self.la7.setObjectName("la7")
        self.le7 = QtWidgets.QLabel(self.centralwidget)
        self.le7.setGeometry(QtCore.QRect(330, 250, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.le7.setFont(font)
        self.le7.setObjectName("le7")
        self.ld7 = QtWidgets.QLabel(self.centralwidget)
        self.ld7.setGeometry(QtCore.QRect(330, 210, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.ld7.setFont(font)
        self.ld7.setObjectName("ld7")
        self.lb7 = QtWidgets.QLabel(self.centralwidget)
        self.lb7.setGeometry(QtCore.QRect(330, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lb7.setFont(font)
        self.lb7.setObjectName("lb7")
        self.li7 = QtWidgets.QLabel(self.centralwidget)
        self.li7.setGeometry(QtCore.QRect(330, 410, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.li7.setFont(font)
        self.li7.setObjectName("li7")
        self.lf7 = QtWidgets.QLabel(self.centralwidget)
        self.lf7.setGeometry(QtCore.QRect(330, 290, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lf7.setFont(font)
        self.lf7.setObjectName("lf7")
        self.lj7 = QtWidgets.QLabel(self.centralwidget)
        self.lj7.setGeometry(QtCore.QRect(330, 450, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lj7.setFont(font)
        self.lj7.setObjectName("lj7")
        self.lh8 = QtWidgets.QLabel(self.centralwidget)
        self.lh8.setGeometry(QtCore.QRect(370, 370, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lh8.setFont(font)
        self.lh8.setObjectName("lh8")
        self.lg8 = QtWidgets.QLabel(self.centralwidget)
        self.lg8.setGeometry(QtCore.QRect(370, 330, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lg8.setFont(font)
        self.lg8.setObjectName("lg8")
        self.label_93 = QtWidgets.QLabel(self.centralwidget)
        self.label_93.setGeometry(QtCore.QRect(370, 490, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_93.setFont(font)
        self.label_93.setObjectName("label_93")
        self.lc8 = QtWidgets.QLabel(self.centralwidget)
        self.lc8.setGeometry(QtCore.QRect(370, 170, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lc8.setFont(font)
        self.lc8.setObjectName("lc8")
        self.la8 = QtWidgets.QLabel(self.centralwidget)
        self.la8.setGeometry(QtCore.QRect(370, 90, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.la8.setFont(font)
        self.la8.setObjectName("la8")
        self.le8 = QtWidgets.QLabel(self.centralwidget)
        self.le8.setGeometry(QtCore.QRect(370, 250, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.le8.setFont(font)
        self.le8.setObjectName("le8")
        self.ld8 = QtWidgets.QLabel(self.centralwidget)
        self.ld8.setGeometry(QtCore.QRect(370, 210, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.ld8.setFont(font)
        self.ld8.setObjectName("ld8")
        self.lb8 = QtWidgets.QLabel(self.centralwidget)
        self.lb8.setGeometry(QtCore.QRect(370, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lb8.setFont(font)
        self.lb8.setObjectName("lb8")
        self.li8 = QtWidgets.QLabel(self.centralwidget)
        self.li8.setGeometry(QtCore.QRect(370, 410, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.li8.setFont(font)
        self.li8.setObjectName("li8")
        self.lf8 = QtWidgets.QLabel(self.centralwidget)
        self.lf8.setGeometry(QtCore.QRect(370, 290, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lf8.setFont(font)
        self.lf8.setObjectName("lf8")
        self.lj8 = QtWidgets.QLabel(self.centralwidget)
        self.lj8.setGeometry(QtCore.QRect(370, 450, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lj8.setFont(font)
        self.lj8.setObjectName("lj8")
        self.lh9 = QtWidgets.QLabel(self.centralwidget)
        self.lh9.setGeometry(QtCore.QRect(410, 370, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lh9.setFont(font)
        self.lh9.setObjectName("lh9")
        self.lg9 = QtWidgets.QLabel(self.centralwidget)
        self.lg9.setGeometry(QtCore.QRect(410, 330, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lg9.setFont(font)
        self.lg9.setObjectName("lg9")
        self.label_104 = QtWidgets.QLabel(self.centralwidget)
        self.label_104.setGeometry(QtCore.QRect(410, 490, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_104.setFont(font)
        self.label_104.setObjectName("label_104")
        self.lc9 = QtWidgets.QLabel(self.centralwidget)
        self.lc9.setGeometry(QtCore.QRect(410, 170, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lc9.setFont(font)
        self.lc9.setObjectName("lc9")
        self.la9 = QtWidgets.QLabel(self.centralwidget)
        self.la9.setGeometry(QtCore.QRect(410, 90, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.la9.setFont(font)
        self.la9.setObjectName("la9")
        self.le9 = QtWidgets.QLabel(self.centralwidget)
        self.le9.setGeometry(QtCore.QRect(410, 250, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.le9.setFont(font)
        self.le9.setObjectName("le9")
        self.ld9 = QtWidgets.QLabel(self.centralwidget)
        self.ld9.setGeometry(QtCore.QRect(410, 210, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.ld9.setFont(font)
        self.ld9.setObjectName("ld9")
        self.lb9 = QtWidgets.QLabel(self.centralwidget)
        self.lb9.setGeometry(QtCore.QRect(410, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lb9.setFont(font)
        self.lb9.setObjectName("lb9")
        self.li9 = QtWidgets.QLabel(self.centralwidget)
        self.li9.setGeometry(QtCore.QRect(410, 410, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.li9.setFont(font)
        self.li9.setObjectName("li9")
        self.lf9 = QtWidgets.QLabel(self.centralwidget)
        self.lf9.setGeometry(QtCore.QRect(410, 290, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lf9.setFont(font)
        self.lf9.setObjectName("lf9")
        self.lj9 = QtWidgets.QLabel(self.centralwidget)
        self.lj9.setGeometry(QtCore.QRect(410, 450, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lj9.setFont(font)
        self.lj9.setObjectName("lj9")
        self.lh10 = QtWidgets.QLabel(self.centralwidget)
        self.lh10.setGeometry(QtCore.QRect(450, 370, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lh10.setFont(font)
        self.lh10.setObjectName("lh10")
        self.lg10 = QtWidgets.QLabel(self.centralwidget)
        self.lg10.setGeometry(QtCore.QRect(450, 330, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lg10.setFont(font)
        self.lg10.setObjectName("lg10")
        self.label_115 = QtWidgets.QLabel(self.centralwidget)
        self.label_115.setGeometry(QtCore.QRect(450, 490, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_115.setFont(font)
        self.label_115.setObjectName("label_115")
        self.lc10 = QtWidgets.QLabel(self.centralwidget)
        self.lc10.setGeometry(QtCore.QRect(450, 170, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lc10.setFont(font)
        self.lc10.setObjectName("lc10")
        self.la10 = QtWidgets.QLabel(self.centralwidget)
        self.la10.setGeometry(QtCore.QRect(450, 90, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.la10.setFont(font)
        self.la10.setObjectName("la10")
        self.le10 = QtWidgets.QLabel(self.centralwidget)
        self.le10.setGeometry(QtCore.QRect(450, 250, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.le10.setFont(font)
        self.le10.setObjectName("le10")
        self.ld10 = QtWidgets.QLabel(self.centralwidget)
        self.ld10.setGeometry(QtCore.QRect(450, 210, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.ld10.setFont(font)
        self.ld10.setObjectName("ld10")
        self.lb10 = QtWidgets.QLabel(self.centralwidget)
        self.lb10.setGeometry(QtCore.QRect(450, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lb10.setFont(font)
        self.lb10.setObjectName("lb10")
        self.li10 = QtWidgets.QLabel(self.centralwidget)
        self.li10.setGeometry(QtCore.QRect(450, 410, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.li10.setFont(font)
        self.li10.setObjectName("li10")
        self.lf10 = QtWidgets.QLabel(self.centralwidget)
        self.lf10.setGeometry(QtCore.QRect(450, 290, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lf10.setFont(font)
        self.lf10.setObjectName("lf10")
        self.lj10 = QtWidgets.QLabel(self.centralwidget)
        self.lj10.setGeometry(QtCore.QRect(450, 450, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lj10.setFont(font)
        self.lj10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lj10.setObjectName("lj10")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(520, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_127 = QtWidgets.QLabel(self.centralwidget)
        self.label_127.setGeometry(QtCore.QRect(670, 490, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_127.setFont(font)
        self.label_127.setObjectName("label_127")
        self.label_130 = QtWidgets.QLabel(self.centralwidget)
        self.label_130.setGeometry(QtCore.QRect(590, 490, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_130.setFont(font)
        self.label_130.setObjectName("label_130")
        self.label_146 = QtWidgets.QLabel(self.centralwidget)
        self.label_146.setGeometry(QtCore.QRect(550, 490, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_146.setFont(font)
        self.label_146.setObjectName("label_146")
        self.label_149 = QtWidgets.QLabel(self.centralwidget)
        self.label_149.setGeometry(QtCore.QRect(520, 290, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_149.setFont(font)
        self.label_149.setObjectName("label_149")
        self.label_154 = QtWidgets.QLabel(self.centralwidget)
        self.label_154.setGeometry(QtCore.QRect(910, 490, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_154.setFont(font)
        self.label_154.setObjectName("label_154")
        self.label_157 = QtWidgets.QLabel(self.centralwidget)
        self.label_157.setGeometry(QtCore.QRect(630, 490, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_157.setFont(font)
        self.label_157.setObjectName("label_157")
        self.label_184 = QtWidgets.QLabel(self.centralwidget)
        self.label_184.setGeometry(QtCore.QRect(870, 490, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_184.setFont(font)
        self.label_184.setObjectName("label_184")
        self.label_189 = QtWidgets.QLabel(self.centralwidget)
        self.label_189.setGeometry(QtCore.QRect(830, 490, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_189.setFont(font)
        self.label_189.setObjectName("label_189")
        self.label_193 = QtWidgets.QLabel(self.centralwidget)
        self.label_193.setGeometry(QtCore.QRect(520, 330, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_193.setFont(font)
        self.label_193.setObjectName("label_193")
        self.label_202 = QtWidgets.QLabel(self.centralwidget)
        self.label_202.setGeometry(QtCore.QRect(520, 250, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_202.setFont(font)
        self.label_202.setObjectName("label_202")
        self.label_203 = QtWidgets.QLabel(self.centralwidget)
        self.label_203.setGeometry(QtCore.QRect(520, 410, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_203.setFont(font)
        self.label_203.setObjectName("label_203")
        self.label_207 = QtWidgets.QLabel(self.centralwidget)
        self.label_207.setGeometry(QtCore.QRect(750, 490, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_207.setFont(font)
        self.label_207.setObjectName("label_207")
        self.label_211 = QtWidgets.QLabel(self.centralwidget)
        self.label_211.setGeometry(QtCore.QRect(790, 490, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_211.setFont(font)
        self.label_211.setObjectName("label_211")
        self.label_217 = QtWidgets.QLabel(self.centralwidget)
        self.label_217.setGeometry(QtCore.QRect(520, 90, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_217.setFont(font)
        self.label_217.setObjectName("label_217")
        self.label_218 = QtWidgets.QLabel(self.centralwidget)
        self.label_218.setGeometry(QtCore.QRect(520, 170, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_218.setFont(font)
        self.label_218.setObjectName("label_218")
        self.label_221 = QtWidgets.QLabel(self.centralwidget)
        self.label_221.setGeometry(QtCore.QRect(520, 210, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_221.setFont(font)
        self.label_221.setObjectName("label_221")
        self.label_222 = QtWidgets.QLabel(self.centralwidget)
        self.label_222.setGeometry(QtCore.QRect(520, 370, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_222.setFont(font)
        self.label_222.setObjectName("label_222")
        self.label_227 = QtWidgets.QLabel(self.centralwidget)
        self.label_227.setGeometry(QtCore.QRect(520, 450, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_227.setFont(font)
        self.label_227.setObjectName("label_227")
        self.label_230 = QtWidgets.QLabel(self.centralwidget)
        self.label_230.setGeometry(QtCore.QRect(710, 490, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_230.setFont(font)
        self.label_230.setObjectName("label_230")
        self.Bj1 = QtWidgets.QPushButton(self.centralwidget)
        self.Bj1.setGeometry(QtCore.QRect(550, 450, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bj1.setFont(font)
        self.Bj1.setObjectName("Bj1")
        self.Bh1 = QtWidgets.QPushButton(self.centralwidget)
        self.Bh1.setGeometry(QtCore.QRect(550, 370, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bh1.setFont(font)
        self.Bh1.setObjectName("Bh1")
        self.Bi1 = QtWidgets.QPushButton(self.centralwidget)
        self.Bi1.setGeometry(QtCore.QRect(550, 410, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bi1.setFont(font)
        self.Bi1.setObjectName("Bi1")
        self.Bg1 = QtWidgets.QPushButton(self.centralwidget)
        self.Bg1.setGeometry(QtCore.QRect(550, 330, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bg1.setFont(font)
        self.Bg1.setObjectName("Bg1")
        self.Bf1 = QtWidgets.QPushButton(self.centralwidget)
        self.Bf1.setGeometry(QtCore.QRect(550, 290, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bf1.setFont(font)
        self.Bf1.setObjectName("Bf1")
        self.Be1 = QtWidgets.QPushButton(self.centralwidget)
        self.Be1.setGeometry(QtCore.QRect(550, 250, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Be1.setFont(font)
        self.Be1.setObjectName("Be1")
        self.Bd1 = QtWidgets.QPushButton(self.centralwidget)
        self.Bd1.setGeometry(QtCore.QRect(550, 210, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bd1.setFont(font)
        self.Bd1.setObjectName("Bd1")
        self.Bc1 = QtWidgets.QPushButton(self.centralwidget)
        self.Bc1.setGeometry(QtCore.QRect(550, 170, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bc1.setFont(font)
        self.Bc1.setObjectName("Bc1")
        self.Bb1 = QtWidgets.QPushButton(self.centralwidget)
        self.Bb1.setGeometry(QtCore.QRect(550, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bb1.setFont(font)
        self.Bb1.setObjectName("Bb1")
        self.Ba1 = QtWidgets.QPushButton(self.centralwidget)
        self.Ba1.setGeometry(QtCore.QRect(550, 90, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Ba1.setFont(font)
        self.Ba1.setObjectName("Ba1")
        self.Bb2 = QtWidgets.QPushButton(self.centralwidget)
        self.Bb2.setGeometry(QtCore.QRect(590, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bb2.setFont(font)
        self.Bb2.setObjectName("Bb2")
        self.Be2 = QtWidgets.QPushButton(self.centralwidget)
        self.Be2.setGeometry(QtCore.QRect(590, 250, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Be2.setFont(font)
        self.Be2.setObjectName("Be2")
        self.Bi2 = QtWidgets.QPushButton(self.centralwidget)
        self.Bi2.setGeometry(QtCore.QRect(590, 410, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bi2.setFont(font)
        self.Bi2.setObjectName("Bi2")
        self.Bc2 = QtWidgets.QPushButton(self.centralwidget)
        self.Bc2.setGeometry(QtCore.QRect(590, 170, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bc2.setFont(font)
        self.Bc2.setObjectName("Bc2")
        self.Bg2 = QtWidgets.QPushButton(self.centralwidget)
        self.Bg2.setGeometry(QtCore.QRect(590, 330, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bg2.setFont(font)
        self.Bg2.setObjectName("Bg2")
        self.Bf2 = QtWidgets.QPushButton(self.centralwidget)
        self.Bf2.setGeometry(QtCore.QRect(590, 290, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bf2.setFont(font)
        self.Bf2.setObjectName("Bf2")
        self.Bj2 = QtWidgets.QPushButton(self.centralwidget)
        self.Bj2.setGeometry(QtCore.QRect(590, 450, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bj2.setFont(font)
        self.Bj2.setObjectName("Bj2")
        self.Bh2 = QtWidgets.QPushButton(self.centralwidget)
        self.Bh2.setGeometry(QtCore.QRect(590, 370, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bh2.setFont(font)
        self.Bh2.setObjectName("Bh2")
        self.Ba2 = QtWidgets.QPushButton(self.centralwidget)
        self.Ba2.setGeometry(QtCore.QRect(590, 90, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Ba2.setFont(font)
        self.Ba2.setObjectName("Ba2")
        self.Bd2 = QtWidgets.QPushButton(self.centralwidget)
        self.Bd2.setGeometry(QtCore.QRect(590, 210, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bd2.setFont(font)
        self.Bd2.setObjectName("Bd2")
        self.Bi3 = QtWidgets.QPushButton(self.centralwidget)
        self.Bi3.setGeometry(QtCore.QRect(630, 410, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bi3.setFont(font)
        self.Bi3.setObjectName("Bi3")
        self.Bb3 = QtWidgets.QPushButton(self.centralwidget)
        self.Bb3.setGeometry(QtCore.QRect(630, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bb3.setFont(font)
        self.Bb3.setObjectName("Bb3")
        self.Bi4 = QtWidgets.QPushButton(self.centralwidget)
        self.Bi4.setGeometry(QtCore.QRect(670, 410, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bi4.setFont(font)
        self.Bi4.setObjectName("Bi4")
        self.Bc3 = QtWidgets.QPushButton(self.centralwidget)
        self.Bc3.setGeometry(QtCore.QRect(630, 170, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bc3.setFont(font)
        self.Bc3.setObjectName("Bc3")
        self.Bh3 = QtWidgets.QPushButton(self.centralwidget)
        self.Bh3.setGeometry(QtCore.QRect(630, 370, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bh3.setFont(font)
        self.Bh3.setObjectName("Bh3")
        self.Bf4 = QtWidgets.QPushButton(self.centralwidget)
        self.Bf4.setGeometry(QtCore.QRect(670, 290, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bf4.setFont(font)
        self.Bf4.setObjectName("Bf4")
        self.Bf3 = QtWidgets.QPushButton(self.centralwidget)
        self.Bf3.setGeometry(QtCore.QRect(630, 290, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bf3.setFont(font)
        self.Bf3.setObjectName("Bf3")
        self.Bh4 = QtWidgets.QPushButton(self.centralwidget)
        self.Bh4.setGeometry(QtCore.QRect(670, 370, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bh4.setFont(font)
        self.Bh4.setObjectName("Bh4")
        self.Bc4 = QtWidgets.QPushButton(self.centralwidget)
        self.Bc4.setGeometry(QtCore.QRect(670, 170, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bc4.setFont(font)
        self.Bc4.setObjectName("Bc4")
        self.Bj3 = QtWidgets.QPushButton(self.centralwidget)
        self.Bj3.setGeometry(QtCore.QRect(630, 450, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bj3.setFont(font)
        self.Bj3.setObjectName("Bj3")
        self.Bd3 = QtWidgets.QPushButton(self.centralwidget)
        self.Bd3.setGeometry(QtCore.QRect(630, 210, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bd3.setFont(font)
        self.Bd3.setObjectName("Bd3")
        self.Bd4 = QtWidgets.QPushButton(self.centralwidget)
        self.Bd4.setGeometry(QtCore.QRect(670, 210, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bd4.setFont(font)
        self.Bd4.setObjectName("Bd4")
        self.Be3 = QtWidgets.QPushButton(self.centralwidget)
        self.Be3.setGeometry(QtCore.QRect(630, 250, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Be3.setFont(font)
        self.Be3.setObjectName("Be3")
        self.Bb4 = QtWidgets.QPushButton(self.centralwidget)
        self.Bb4.setGeometry(QtCore.QRect(670, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bb4.setFont(font)
        self.Bb4.setObjectName("Bb4")
        self.Bj4 = QtWidgets.QPushButton(self.centralwidget)
        self.Bj4.setGeometry(QtCore.QRect(670, 450, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bj4.setFont(font)
        self.Bj4.setObjectName("Bj4")
        self.Ba3 = QtWidgets.QPushButton(self.centralwidget)
        self.Ba3.setGeometry(QtCore.QRect(630, 90, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Ba3.setFont(font)
        self.Ba3.setObjectName("Ba3")
        self.Bg3 = QtWidgets.QPushButton(self.centralwidget)
        self.Bg3.setGeometry(QtCore.QRect(630, 330, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bg3.setFont(font)
        self.Bg3.setObjectName("Bg3")
        self.Bg4 = QtWidgets.QPushButton(self.centralwidget)
        self.Bg4.setGeometry(QtCore.QRect(670, 330, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bg4.setFont(font)
        self.Bg4.setObjectName("Bg4")
        self.Ba4 = QtWidgets.QPushButton(self.centralwidget)
        self.Ba4.setGeometry(QtCore.QRect(670, 90, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Ba4.setFont(font)
        self.Ba4.setObjectName("Ba4")
        self.Be4 = QtWidgets.QPushButton(self.centralwidget)
        self.Be4.setGeometry(QtCore.QRect(670, 250, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Be4.setFont(font)
        self.Be4.setObjectName("Be4")
        self.Bi5 = QtWidgets.QPushButton(self.centralwidget)
        self.Bi5.setGeometry(QtCore.QRect(710, 410, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bi5.setFont(font)
        self.Bi5.setObjectName("Bi5")
        self.Bb5 = QtWidgets.QPushButton(self.centralwidget)
        self.Bb5.setGeometry(QtCore.QRect(710, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bb5.setFont(font)
        self.Bb5.setObjectName("Bb5")
        self.Bi6 = QtWidgets.QPushButton(self.centralwidget)
        self.Bi6.setGeometry(QtCore.QRect(750, 410, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bi6.setFont(font)
        self.Bi6.setObjectName("Bi6")
        self.Bc5 = QtWidgets.QPushButton(self.centralwidget)
        self.Bc5.setGeometry(QtCore.QRect(710, 170, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bc5.setFont(font)
        self.Bc5.setObjectName("Bc5")
        self.Bh5 = QtWidgets.QPushButton(self.centralwidget)
        self.Bh5.setGeometry(QtCore.QRect(710, 370, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bh5.setFont(font)
        self.Bh5.setObjectName("Bh5")
        self.Bf6 = QtWidgets.QPushButton(self.centralwidget)
        self.Bf6.setGeometry(QtCore.QRect(750, 290, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bf6.setFont(font)
        self.Bf6.setObjectName("Bf6")
        self.Bf5 = QtWidgets.QPushButton(self.centralwidget)
        self.Bf5.setGeometry(QtCore.QRect(710, 290, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bf5.setFont(font)
        self.Bf5.setObjectName("Bf5")
        self.Bh6 = QtWidgets.QPushButton(self.centralwidget)
        self.Bh6.setGeometry(QtCore.QRect(750, 370, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bh6.setFont(font)
        self.Bh6.setObjectName("Bh6")
        self.Bc6 = QtWidgets.QPushButton(self.centralwidget)
        self.Bc6.setGeometry(QtCore.QRect(750, 170, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bc6.setFont(font)
        self.Bc6.setObjectName("Bc6")
        self.Bj5 = QtWidgets.QPushButton(self.centralwidget)
        self.Bj5.setGeometry(QtCore.QRect(710, 450, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bj5.setFont(font)
        self.Bj5.setObjectName("Bj5")
        self.Bd5 = QtWidgets.QPushButton(self.centralwidget)
        self.Bd5.setGeometry(QtCore.QRect(710, 210, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bd5.setFont(font)
        self.Bd5.setObjectName("Bd5")
        self.Bd6 = QtWidgets.QPushButton(self.centralwidget)
        self.Bd6.setGeometry(QtCore.QRect(750, 210, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bd6.setFont(font)
        self.Bd6.setObjectName("Bd6")
        self.Be5 = QtWidgets.QPushButton(self.centralwidget)
        self.Be5.setGeometry(QtCore.QRect(710, 250, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Be5.setFont(font)
        self.Be5.setObjectName("Be5")
        self.Bb6 = QtWidgets.QPushButton(self.centralwidget)
        self.Bb6.setGeometry(QtCore.QRect(750, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bb6.setFont(font)
        self.Bb6.setObjectName("Bb6")
        self.Bj6 = QtWidgets.QPushButton(self.centralwidget)
        self.Bj6.setGeometry(QtCore.QRect(750, 450, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bj6.setFont(font)
        self.Bj6.setObjectName("Bj6")
        self.Ba5 = QtWidgets.QPushButton(self.centralwidget)
        self.Ba5.setGeometry(QtCore.QRect(710, 90, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Ba5.setFont(font)
        self.Ba5.setObjectName("Ba5")
        self.Bg5 = QtWidgets.QPushButton(self.centralwidget)
        self.Bg5.setGeometry(QtCore.QRect(710, 330, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bg5.setFont(font)
        self.Bg5.setObjectName("Bg5")
        self.Bg6 = QtWidgets.QPushButton(self.centralwidget)
        self.Bg6.setGeometry(QtCore.QRect(750, 330, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bg6.setFont(font)
        self.Bg6.setObjectName("Bg6")
        self.Ba6 = QtWidgets.QPushButton(self.centralwidget)
        self.Ba6.setGeometry(QtCore.QRect(750, 90, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Ba6.setFont(font)
        self.Ba6.setObjectName("Ba6")
        self.Be6 = QtWidgets.QPushButton(self.centralwidget)
        self.Be6.setGeometry(QtCore.QRect(750, 250, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Be6.setFont(font)
        self.Be6.setObjectName("Be6")
        self.Bi7 = QtWidgets.QPushButton(self.centralwidget)
        self.Bi7.setGeometry(QtCore.QRect(790, 410, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bi7.setFont(font)
        self.Bi7.setObjectName("Bi7")
        self.Bb7 = QtWidgets.QPushButton(self.centralwidget)
        self.Bb7.setGeometry(QtCore.QRect(790, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bb7.setFont(font)
        self.Bb7.setObjectName("Bb7")
        self.Bi8 = QtWidgets.QPushButton(self.centralwidget)
        self.Bi8.setGeometry(QtCore.QRect(830, 410, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bi8.setFont(font)
        self.Bi8.setObjectName("Bi8")
        self.Bc7 = QtWidgets.QPushButton(self.centralwidget)
        self.Bc7.setGeometry(QtCore.QRect(790, 170, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bc7.setFont(font)
        self.Bc7.setObjectName("Bc7")
        self.Bh7 = QtWidgets.QPushButton(self.centralwidget)
        self.Bh7.setGeometry(QtCore.QRect(790, 370, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bh7.setFont(font)
        self.Bh7.setObjectName("Bh7")
        self.Bf8 = QtWidgets.QPushButton(self.centralwidget)
        self.Bf8.setGeometry(QtCore.QRect(830, 290, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bf8.setFont(font)
        self.Bf8.setObjectName("Bf8")
        self.Bf7 = QtWidgets.QPushButton(self.centralwidget)
        self.Bf7.setGeometry(QtCore.QRect(790, 290, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bf7.setFont(font)
        self.Bf7.setObjectName("Bf7")
        self.Bh8 = QtWidgets.QPushButton(self.centralwidget)
        self.Bh8.setGeometry(QtCore.QRect(830, 370, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bh8.setFont(font)
        self.Bh8.setObjectName("Bh8")
        self.Bc8 = QtWidgets.QPushButton(self.centralwidget)
        self.Bc8.setGeometry(QtCore.QRect(830, 170, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bc8.setFont(font)
        self.Bc8.setObjectName("Bc8")
        self.Bj7 = QtWidgets.QPushButton(self.centralwidget)
        self.Bj7.setGeometry(QtCore.QRect(790, 450, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bj7.setFont(font)
        self.Bj7.setObjectName("Bj7")
        self.Bd7 = QtWidgets.QPushButton(self.centralwidget)
        self.Bd7.setGeometry(QtCore.QRect(790, 210, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bd7.setFont(font)
        self.Bd7.setObjectName("Bd7")
        self.Bd8 = QtWidgets.QPushButton(self.centralwidget)
        self.Bd8.setGeometry(QtCore.QRect(830, 210, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bd8.setFont(font)
        self.Bd8.setObjectName("Bd8")
        self.Be7 = QtWidgets.QPushButton(self.centralwidget)
        self.Be7.setGeometry(QtCore.QRect(790, 250, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Be7.setFont(font)
        self.Be7.setObjectName("Be7")
        self.Bb8 = QtWidgets.QPushButton(self.centralwidget)
        self.Bb8.setGeometry(QtCore.QRect(830, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bb8.setFont(font)
        self.Bb8.setObjectName("Bb8")
        self.Bj8 = QtWidgets.QPushButton(self.centralwidget)
        self.Bj8.setGeometry(QtCore.QRect(830, 450, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bj8.setFont(font)
        self.Bj8.setObjectName("Bj8")
        self.Ba7 = QtWidgets.QPushButton(self.centralwidget)
        self.Ba7.setGeometry(QtCore.QRect(790, 90, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Ba7.setFont(font)
        self.Ba7.setObjectName("Ba7")
        self.Bg7 = QtWidgets.QPushButton(self.centralwidget)
        self.Bg7.setGeometry(QtCore.QRect(790, 330, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bg7.setFont(font)
        self.Bg7.setObjectName("Bg7")
        self.Bg8 = QtWidgets.QPushButton(self.centralwidget)
        self.Bg8.setGeometry(QtCore.QRect(830, 330, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bg8.setFont(font)
        self.Bg8.setObjectName("Bg8")
        self.Ba8 = QtWidgets.QPushButton(self.centralwidget)
        self.Ba8.setGeometry(QtCore.QRect(830, 90, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Ba8.setFont(font)
        self.Ba8.setObjectName("Ba8")
        self.Be8 = QtWidgets.QPushButton(self.centralwidget)
        self.Be8.setGeometry(QtCore.QRect(830, 250, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Be8.setFont(font)
        self.Be8.setObjectName("Be8")
        self.Bi9 = QtWidgets.QPushButton(self.centralwidget)
        self.Bi9.setGeometry(QtCore.QRect(870, 410, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bi9.setFont(font)
        self.Bi9.setObjectName("Bi9")
        self.Bb9 = QtWidgets.QPushButton(self.centralwidget)
        self.Bb9.setGeometry(QtCore.QRect(870, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bb9.setFont(font)
        self.Bb9.setObjectName("Bb9")
        self.Bi10 = QtWidgets.QPushButton(self.centralwidget)
        self.Bi10.setGeometry(QtCore.QRect(910, 410, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bi10.setFont(font)
        self.Bi10.setObjectName("Bi10")
        self.Bc9 = QtWidgets.QPushButton(self.centralwidget)
        self.Bc9.setGeometry(QtCore.QRect(870, 170, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bc9.setFont(font)
        self.Bc9.setObjectName("Bc9")
        self.Bh9 = QtWidgets.QPushButton(self.centralwidget)
        self.Bh9.setGeometry(QtCore.QRect(870, 370, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bh9.setFont(font)
        self.Bh9.setObjectName("Bh9")
        self.Bf10 = QtWidgets.QPushButton(self.centralwidget)
        self.Bf10.setGeometry(QtCore.QRect(910, 290, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bf10.setFont(font)
        self.Bf10.setObjectName("Bf10")
        self.Bf9 = QtWidgets.QPushButton(self.centralwidget)
        self.Bf9.setGeometry(QtCore.QRect(870, 290, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bf9.setFont(font)
        self.Bf9.setObjectName("Bf9")
        self.Bh10 = QtWidgets.QPushButton(self.centralwidget)
        self.Bh10.setGeometry(QtCore.QRect(910, 370, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bh10.setFont(font)
        self.Bh10.setObjectName("Bh10")
        self.Bc10 = QtWidgets.QPushButton(self.centralwidget)
        self.Bc10.setGeometry(QtCore.QRect(910, 170, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bc10.setFont(font)
        self.Bc10.setObjectName("Bc10")
        self.Bj9 = QtWidgets.QPushButton(self.centralwidget)
        self.Bj9.setGeometry(QtCore.QRect(870, 450, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bj9.setFont(font)
        self.Bj9.setObjectName("Bj9")
        self.Bd9 = QtWidgets.QPushButton(self.centralwidget)
        self.Bd9.setGeometry(QtCore.QRect(870, 210, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bd9.setFont(font)
        self.Bd9.setObjectName("Bd9")
        self.Bd10 = QtWidgets.QPushButton(self.centralwidget)
        self.Bd10.setGeometry(QtCore.QRect(910, 210, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bd10.setFont(font)
        self.Bd10.setObjectName("Bd10")
        self.Be9 = QtWidgets.QPushButton(self.centralwidget)
        self.Be9.setGeometry(QtCore.QRect(870, 250, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Be9.setFont(font)
        self.Be9.setObjectName("Be9")
        self.Bb10 = QtWidgets.QPushButton(self.centralwidget)
        self.Bb10.setGeometry(QtCore.QRect(910, 130, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bb10.setFont(font)
        self.Bb10.setObjectName("Bb10")
        self.Bj10 = QtWidgets.QPushButton(self.centralwidget)
        self.Bj10.setGeometry(QtCore.QRect(910, 450, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bj10.setFont(font)
        self.Bj10.setObjectName("Bj10")
        self.Ba9 = QtWidgets.QPushButton(self.centralwidget)
        self.Ba9.setGeometry(QtCore.QRect(870, 90, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Ba9.setFont(font)
        self.Ba9.setObjectName("Ba9")
        self.Bg9 = QtWidgets.QPushButton(self.centralwidget)
        self.Bg9.setGeometry(QtCore.QRect(870, 330, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bg9.setFont(font)
        self.Bg9.setObjectName("Bg9")
        self.Bg10 = QtWidgets.QPushButton(self.centralwidget)
        self.Bg10.setGeometry(QtCore.QRect(910, 330, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bg10.setFont(font)
        self.Bg10.setObjectName("Bg10")
        self.Ba10 = QtWidgets.QPushButton(self.centralwidget)
        self.Ba10.setGeometry(QtCore.QRect(910, 90, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Ba10.setFont(font)
        self.Ba10.setObjectName("Ba10")
        self.Be10 = QtWidgets.QPushButton(self.centralwidget)
        self.Be10.setGeometry(QtCore.QRect(910, 250, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Be10.setFont(font)
        self.Be10.setObjectName("Be10")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(980, 90, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(980, 120, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(980, 150, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(980, 180, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(1050, 30, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(980, 300, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(980, 340, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(980, 380, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(980, 210, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_turn = QtWidgets.QLabel(self.centralwidget)
        self.label_turn.setGeometry(QtCore.QRect(420, 540, 551, 61))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_turn.setFont(font)
        self.label_turn.setObjectName("label_turn")
        self.label_turn2 = QtWidgets.QLabel(self.centralwidget)
        self.label_turn2.setGeometry(QtCore.QRect(270, 610, 871, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_turn2.setFont(font)
        self.label_turn2.setText("")
        self.label_turn2.setObjectName("label_turn2")
        SeaBattle.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SeaBattle)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1358, 23))
        self.menubar.setObjectName("menubar")
        SeaBattle.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SeaBattle)
        self.statusbar.setObjectName("statusbar")
        SeaBattle.setStatusBar(self.statusbar)

        self.retranslateUi2(SeaBattle)
        QtCore.QMetaObject.connectSlotsByName(SeaBattle)

    def retranslateUi2(self, SeaBattle):
        _translate = QtCore.QCoreApplication.translate
        SeaBattle.setWindowTitle(_translate("SeaBattle", "MainWindow"))
        self.label.setText(_translate("SeaBattle", "Ваше поле"))
        self.label_2.setText(_translate("SeaBattle", "Поле компьютера"))
        self.label_3.setText(_translate("SeaBattle", "a"))
        self.label_4.setText(_translate("SeaBattle", "b"))
        self.label_5.setText(_translate("SeaBattle", "c"))
        self.label_6.setText(_translate("SeaBattle", "e"))
        self.label_7.setText(_translate("SeaBattle", "d"))
        self.label_8.setText(_translate("SeaBattle", "f"))
        self.label_9.setText(_translate("SeaBattle", "g"))
        self.label_10.setText(_translate("SeaBattle", "h"))
        self.label_11.setText(_translate("SeaBattle", "i"))
        self.label_12.setText(_translate("SeaBattle", "j"))
        self.lh1.setText(_translate("SeaBattle", " -"))
        self.lg1.setText(_translate("SeaBattle", " -"))
        self.label_16.setText(_translate("SeaBattle", "  1"))
        self.lc1.setText(_translate("SeaBattle", " -"))
        self.la1.setText(_translate("SeaBattle", " -"))
        self.le1.setText(_translate("SeaBattle", " -"))
        self.ld1.setText(_translate("SeaBattle", " -"))
        self.lb1.setText(_translate("SeaBattle", " -"))
        self.li1.setText(_translate("SeaBattle", " -"))
        self.lf1.setText(_translate("SeaBattle", " -"))
        self.lj1.setText(_translate("SeaBattle", " -"))
        self.lh2.setText(_translate("SeaBattle", " -"))
        self.lg2.setText(_translate("SeaBattle", " -"))
        self.label_27.setText(_translate("SeaBattle", "  2"))
        self.lc2.setText(_translate("SeaBattle", " -"))
        self.la2.setText(_translate("SeaBattle", " -"))
        self.le2.setText(_translate("SeaBattle", " -"))
        self.ld2.setText(_translate("SeaBattle", " -"))
        self.lb2.setText(_translate("SeaBattle", " -"))
        self.li2.setText(_translate("SeaBattle", " -"))
        self.lf2.setText(_translate("SeaBattle", " -"))
        self.lj2.setText(_translate("SeaBattle", " -"))
        self.lh3.setText(_translate("SeaBattle", " -"))
        self.lg3.setText(_translate("SeaBattle", " -"))
        self.label_38.setText(_translate("SeaBattle", "  3"))
        self.lc3.setText(_translate("SeaBattle", " -"))
        self.la3.setText(_translate("SeaBattle", " -"))
        self.le3.setText(_translate("SeaBattle", " -"))
        self.ld3.setText(_translate("SeaBattle", " -"))
        self.lb3.setText(_translate("SeaBattle", " -"))
        self.li3.setText(_translate("SeaBattle", " -"))
        self.lf3.setText(_translate("SeaBattle", " -"))
        self.lj3.setText(_translate("SeaBattle", " -"))
        self.lh4.setText(_translate("SeaBattle", " -"))
        self.lg4.setText(_translate("SeaBattle", " -"))
        self.label_49.setText(_translate("SeaBattle", "  4"))
        self.lc4.setText(_translate("SeaBattle", " -"))
        self.la4.setText(_translate("SeaBattle", " -"))
        self.le4.setText(_translate("SeaBattle", " -"))
        self.ld4.setText(_translate("SeaBattle", " -"))
        self.lb4.setText(_translate("SeaBattle", " -"))
        self.li4.setText(_translate("SeaBattle", " -"))
        self.lf4.setText(_translate("SeaBattle", " -"))
        self.lj4.setText(_translate("SeaBattle", " -"))
        self.lh5.setText(_translate("SeaBattle", " -"))
        self.lg5.setText(_translate("SeaBattle", " -"))
        self.label_60.setText(_translate("SeaBattle", "  5"))
        self.lc5.setText(_translate("SeaBattle", " -"))
        self.la5.setText(_translate("SeaBattle", " -"))
        self.le5.setText(_translate("SeaBattle", " -"))
        self.ld5.setText(_translate("SeaBattle", " -"))
        self.lb5.setText(_translate("SeaBattle", " -"))
        self.li5.setText(_translate("SeaBattle", " -"))
        self.lf5.setText(_translate("SeaBattle", " -"))
        self.lj5.setText(_translate("SeaBattle", " -"))
        self.lh6.setText(_translate("SeaBattle", " -"))
        self.lg6.setText(_translate("SeaBattle", " -"))
        self.label_71.setText(_translate("SeaBattle", "  6"))
        self.lc6.setText(_translate("SeaBattle", " -"))
        self.la6.setText(_translate("SeaBattle", " -"))
        self.le6.setText(_translate("SeaBattle", " -"))
        self.ld6.setText(_translate("SeaBattle", " -"))
        self.lb6.setText(_translate("SeaBattle", " -"))
        self.li6.setText(_translate("SeaBattle", " -"))
        self.lf6.setText(_translate("SeaBattle", " -"))
        self.lj6.setText(_translate("SeaBattle", " -"))
        self.lh7.setText(_translate("SeaBattle", " -"))
        self.lg7.setText(_translate("SeaBattle", " -"))
        self.label_82.setText(_translate("SeaBattle", "  7"))
        self.lc7.setText(_translate("SeaBattle", " -"))
        self.la7.setText(_translate("SeaBattle", " -"))
        self.le7.setText(_translate("SeaBattle", " -"))
        self.ld7.setText(_translate("SeaBattle", " -"))
        self.lb7.setText(_translate("SeaBattle", " -"))
        self.li7.setText(_translate("SeaBattle", " -"))
        self.lf7.setText(_translate("SeaBattle", " -"))
        self.lj7.setText(_translate("SeaBattle", " -"))
        self.lh8.setText(_translate("SeaBattle", " -"))
        self.lg8.setText(_translate("SeaBattle", " -"))
        self.label_93.setText(_translate("SeaBattle", "  8"))
        self.lc8.setText(_translate("SeaBattle", " -"))
        self.la8.setText(_translate("SeaBattle", " -"))
        self.le8.setText(_translate("SeaBattle", " -"))
        self.ld8.setText(_translate("SeaBattle", " -"))
        self.lb8.setText(_translate("SeaBattle", " -"))
        self.li8.setText(_translate("SeaBattle", " -"))
        self.lf8.setText(_translate("SeaBattle", " -"))
        self.lj8.setText(_translate("SeaBattle", " -"))
        self.lh9.setText(_translate("SeaBattle", " -"))
        self.lg9.setText(_translate("SeaBattle", " -"))
        self.label_104.setText(_translate("SeaBattle", "  9"))
        self.lc9.setText(_translate("SeaBattle", " -"))
        self.la9.setText(_translate("SeaBattle", " -"))
        self.le9.setText(_translate("SeaBattle", " -"))
        self.ld9.setText(_translate("SeaBattle", " -"))
        self.lb9.setText(_translate("SeaBattle", " -"))
        self.li9.setText(_translate("SeaBattle", " -"))
        self.lf9.setText(_translate("SeaBattle", " -"))
        self.lj9.setText(_translate("SeaBattle", " -"))
        self.lh10.setText(_translate("SeaBattle", " -"))
        self.lg10.setText(_translate("SeaBattle", " -"))
        self.label_115.setText(_translate("SeaBattle", " 10"))
        self.lc10.setText(_translate("SeaBattle", " -"))
        self.la10.setText(_translate("SeaBattle", " -"))
        self.le10.setText(_translate("SeaBattle", " -"))
        self.ld10.setText(_translate("SeaBattle", " -"))
        self.lb10.setText(_translate("SeaBattle", " -"))
        self.li10.setText(_translate("SeaBattle", " -"))
        self.lf10.setText(_translate("SeaBattle", " -"))
        self.lj10.setText(_translate("SeaBattle", " -"))
        self.label_13.setText(_translate("SeaBattle", "b"))
        self.label_127.setText(_translate("SeaBattle", "  4"))
        self.label_130.setText(_translate("SeaBattle", "  2"))
        self.label_146.setText(_translate("SeaBattle", "  1"))
        self.label_149.setText(_translate("SeaBattle", "f"))
        self.label_154.setText(_translate("SeaBattle", " 10"))
        self.label_157.setText(_translate("SeaBattle", "  3"))
        self.label_184.setText(_translate("SeaBattle", "  9"))
        self.label_189.setText(_translate("SeaBattle", "  8"))
        self.label_193.setText(_translate("SeaBattle", "g"))
        self.label_202.setText(_translate("SeaBattle", "e"))
        self.label_203.setText(_translate("SeaBattle", "i"))
        self.label_207.setText(_translate("SeaBattle", "  6"))
        self.label_211.setText(_translate("SeaBattle", "  7"))
        self.label_217.setText(_translate("SeaBattle", "a"))
        self.label_218.setText(_translate("SeaBattle", "c"))
        self.label_221.setText(_translate("SeaBattle", "d"))
        self.label_222.setText(_translate("SeaBattle", "h"))
        self.label_227.setText(_translate("SeaBattle", "j"))
        self.label_230.setText(_translate("SeaBattle", "  5"))
        self.Bj1.setText(_translate("SeaBattle", "-"))
        self.Bh1.setText(_translate("SeaBattle", "-"))
        self.Bi1.setText(_translate("SeaBattle", "-"))
        self.Bg1.setText(_translate("SeaBattle", "-"))
        self.Bf1.setText(_translate("SeaBattle", "-"))
        self.Be1.setText(_translate("SeaBattle", "-"))
        self.Bd1.setText(_translate("SeaBattle", "-"))
        self.Bc1.setText(_translate("SeaBattle", "-"))
        self.Bb1.setText(_translate("SeaBattle", "-"))
        self.Ba1.setText(_translate("SeaBattle", "-"))
        self.Bb2.setText(_translate("SeaBattle", "-"))
        self.Be2.setText(_translate("SeaBattle", "-"))
        self.Bi2.setText(_translate("SeaBattle", "-"))
        self.Bc2.setText(_translate("SeaBattle", "-"))
        self.Bg2.setText(_translate("SeaBattle", "-"))
        self.Bf2.setText(_translate("SeaBattle", "-"))
        self.Bj2.setText(_translate("SeaBattle", "-"))
        self.Bh2.setText(_translate("SeaBattle", "-"))
        self.Ba2.setText(_translate("SeaBattle", "-"))
        self.Bd2.setText(_translate("SeaBattle", "-"))
        self.Bi3.setText(_translate("SeaBattle", "-"))
        self.Bb3.setText(_translate("SeaBattle", "-"))
        self.Bi4.setText(_translate("SeaBattle", "-"))
        self.Bc3.setText(_translate("SeaBattle", "-"))
        self.Bh3.setText(_translate("SeaBattle", "-"))
        self.Bf4.setText(_translate("SeaBattle", "-"))
        self.Bf3.setText(_translate("SeaBattle", "-"))
        self.Bh4.setText(_translate("SeaBattle", "-"))
        self.Bc4.setText(_translate("SeaBattle", "-"))
        self.Bj3.setText(_translate("SeaBattle", "-"))
        self.Bd3.setText(_translate("SeaBattle", "-"))
        self.Bd4.setText(_translate("SeaBattle", "-"))
        self.Be3.setText(_translate("SeaBattle", "-"))
        self.Bb4.setText(_translate("SeaBattle", "-"))
        self.Bj4.setText(_translate("SeaBattle", "-"))
        self.Ba3.setText(_translate("SeaBattle", "-"))
        self.Bg3.setText(_translate("SeaBattle", "-"))
        self.Bg4.setText(_translate("SeaBattle", "-"))
        self.Ba4.setText(_translate("SeaBattle", "-"))
        self.Be4.setText(_translate("SeaBattle", "-"))
        self.Bi5.setText(_translate("SeaBattle", "-"))
        self.Bb5.setText(_translate("SeaBattle", "-"))
        self.Bi6.setText(_translate("SeaBattle", "-"))
        self.Bc5.setText(_translate("SeaBattle", "-"))
        self.Bh5.setText(_translate("SeaBattle", "-"))
        self.Bf6.setText(_translate("SeaBattle", "-"))
        self.Bf5.setText(_translate("SeaBattle", "-"))
        self.Bh6.setText(_translate("SeaBattle", "-"))
        self.Bc6.setText(_translate("SeaBattle", "-"))
        self.Bj5.setText(_translate("SeaBattle", "-"))
        self.Bd5.setText(_translate("SeaBattle", "-"))
        self.Bd6.setText(_translate("SeaBattle", "-"))
        self.Be5.setText(_translate("SeaBattle", "-"))
        self.Bb6.setText(_translate("SeaBattle", "-"))
        self.Bj6.setText(_translate("SeaBattle", "-"))
        self.Ba5.setText(_translate("SeaBattle", "-"))
        self.Bg5.setText(_translate("SeaBattle", "-"))
        self.Bg6.setText(_translate("SeaBattle", "-"))
        self.Ba6.setText(_translate("SeaBattle", "-"))
        self.Be6.setText(_translate("SeaBattle", "-"))
        self.Bi7.setText(_translate("SeaBattle", "-"))
        self.Bb7.setText(_translate("SeaBattle", "-"))
        self.Bi8.setText(_translate("SeaBattle", "-"))
        self.Bc7.setText(_translate("SeaBattle", "-"))
        self.Bh7.setText(_translate("SeaBattle", "-"))
        self.Bf8.setText(_translate("SeaBattle", "-"))
        self.Bf7.setText(_translate("SeaBattle", "-"))
        self.Bh8.setText(_translate("SeaBattle", "-"))
        self.Bc8.setText(_translate("SeaBattle", "-"))
        self.Bj7.setText(_translate("SeaBattle", "-"))
        self.Bd7.setText(_translate("SeaBattle", "-"))
        self.Bd8.setText(_translate("SeaBattle", "-"))
        self.Be7.setText(_translate("SeaBattle", "-"))
        self.Bb8.setText(_translate("SeaBattle", "-"))
        self.Bj8.setText(_translate("SeaBattle", "-"))
        self.Ba7.setText(_translate("SeaBattle", "-"))
        self.Bg7.setText(_translate("SeaBattle", "-"))
        self.Bg8.setText(_translate("SeaBattle", "-"))
        self.Ba8.setText(_translate("SeaBattle", "-"))
        self.Be8.setText(_translate("SeaBattle", "-"))
        self.Bi9.setText(_translate("SeaBattle", "-"))
        self.Bb9.setText(_translate("SeaBattle", "-"))
        self.Bi10.setText(_translate("SeaBattle", "-"))
        self.Bc9.setText(_translate("SeaBattle", "-"))
        self.Bh9.setText(_translate("SeaBattle", "-"))
        self.Bf10.setText(_translate("SeaBattle", "-"))
        self.Bf9.setText(_translate("SeaBattle", "-"))
        self.Bh10.setText(_translate("SeaBattle", "-"))
        self.Bc10.setText(_translate("SeaBattle", "-"))
        self.Bj9.setText(_translate("SeaBattle", "-"))
        self.Bd9.setText(_translate("SeaBattle", "-"))
        self.Bd10.setText(_translate("SeaBattle", "-"))
        self.Be9.setText(_translate("SeaBattle", "-"))
        self.Bb10.setText(_translate("SeaBattle", "-"))
        self.Bj10.setText(_translate("SeaBattle", "-"))
        self.Ba9.setText(_translate("SeaBattle", "-"))
        self.Bg9.setText(_translate("SeaBattle", "-"))
        self.Bg10.setText(_translate("SeaBattle", "-"))
        self.Ba10.setText(_translate("SeaBattle", "-"))
        self.Be10.setText(_translate("SeaBattle", "-"))
        self.label_14.setText(_translate("SeaBattle", "\"-\" - неизвестная клетка"))
        self.label_15.setText(_translate("SeaBattle", "\"х\" - клетка раненного корабля"))
        self.label_17.setText(_translate("SeaBattle", "\"Х\" - клетка убитого корабля"))
        self.label_18.setText(_translate("SeaBattle", "\"0\" - пустая клетка (промах)"))
        self.label_19.setText(_translate("SeaBattle", "Подсказки:"))
        self.label_20.setText(_translate("SeaBattle", "Чтобы сходить, нажмите на ту"))
        self.label_22.setText(_translate("SeaBattle", "клетку, по которой хотите"))
        self.label_23.setText(_translate("SeaBattle", "выстрелить."))
        self.label_21.setText(_translate("SeaBattle", "\"+\" - клетка вашего корабля"))
        self.label_turn.setText(_translate("SeaBattle", "                     Ваш Ход."))

