# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proj-start.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1361, 720)
        MainWindow.setStyleSheet("background-color: rgb(40, 86, 185)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(640, 640, 87, 29))
        self.pushButton.setObjectName("pushButton")
        self.Bi7 = QtWidgets.QPushButton(self.centralwidget)
        self.Bi7.setGeometry(QtCore.QRect(730, 480, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bi7.setFont(font)
        self.Bi7.setObjectName("Bi7")
        self.Bd1 = QtWidgets.QPushButton(self.centralwidget)
        self.Bd1.setGeometry(QtCore.QRect(490, 280, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bd1.setFont(font)
        self.Bd1.setObjectName("Bd1")
        self.Bd10 = QtWidgets.QPushButton(self.centralwidget)
        self.Bd10.setGeometry(QtCore.QRect(850, 280, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bd10.setFont(font)
        self.Bd10.setObjectName("Bd10")
        self.label_127 = QtWidgets.QLabel(self.centralwidget)
        self.label_127.setGeometry(QtCore.QRect(610, 560, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_127.setFont(font)
        self.label_127.setObjectName("label_127")
        self.Bg4 = QtWidgets.QPushButton(self.centralwidget)
        self.Bg4.setGeometry(QtCore.QRect(610, 400, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bg4.setFont(font)
        self.Bg4.setObjectName("Bg4")
        self.Bj4 = QtWidgets.QPushButton(self.centralwidget)
        self.Bj4.setGeometry(QtCore.QRect(610, 520, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bj4.setFont(font)
        self.Bj4.setObjectName("Bj4")
        self.Bj7 = QtWidgets.QPushButton(self.centralwidget)
        self.Bj7.setGeometry(QtCore.QRect(730, 520, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bj7.setFont(font)
        self.Bj7.setObjectName("Bj7")
        self.label_149 = QtWidgets.QLabel(self.centralwidget)
        self.label_149.setGeometry(QtCore.QRect(460, 360, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_149.setFont(font)
        self.label_149.setObjectName("label_149")
        self.Be8 = QtWidgets.QPushButton(self.centralwidget)
        self.Be8.setGeometry(QtCore.QRect(770, 320, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Be8.setFont(font)
        self.Be8.setObjectName("Be8")
        self.Bd9 = QtWidgets.QPushButton(self.centralwidget)
        self.Bd9.setGeometry(QtCore.QRect(810, 280, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bd9.setFont(font)
        self.Bd9.setObjectName("Bd9")
        self.label_230 = QtWidgets.QLabel(self.centralwidget)
        self.label_230.setGeometry(QtCore.QRect(650, 560, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_230.setFont(font)
        self.label_230.setObjectName("label_230")
        self.Bj3 = QtWidgets.QPushButton(self.centralwidget)
        self.Bj3.setGeometry(QtCore.QRect(570, 520, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bj3.setFont(font)
        self.Bj3.setObjectName("Bj3")
        self.Bc8 = QtWidgets.QPushButton(self.centralwidget)
        self.Bc8.setGeometry(QtCore.QRect(770, 240, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bc8.setFont(font)
        self.Bc8.setObjectName("Bc8")
        self.Bb3 = QtWidgets.QPushButton(self.centralwidget)
        self.Bb3.setGeometry(QtCore.QRect(570, 200, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bb3.setFont(font)
        self.Bb3.setObjectName("Bb3")
        self.Bg1 = QtWidgets.QPushButton(self.centralwidget)
        self.Bg1.setGeometry(QtCore.QRect(490, 400, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bg1.setFont(font)
        self.Bg1.setObjectName("Bg1")
        self.Bh8 = QtWidgets.QPushButton(self.centralwidget)
        self.Bh8.setGeometry(QtCore.QRect(770, 440, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bh8.setFont(font)
        self.Bh8.setObjectName("Bh8")
        self.Bb1 = QtWidgets.QPushButton(self.centralwidget)
        self.Bb1.setGeometry(QtCore.QRect(490, 200, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bb1.setFont(font)
        self.Bb1.setObjectName("Bb1")
        self.Bg3 = QtWidgets.QPushButton(self.centralwidget)
        self.Bg3.setGeometry(QtCore.QRect(570, 400, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bg3.setFont(font)
        self.Bg3.setObjectName("Bg3")
        self.Bf4 = QtWidgets.QPushButton(self.centralwidget)
        self.Bf4.setGeometry(QtCore.QRect(610, 360, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bf4.setFont(font)
        self.Bf4.setObjectName("Bf4")
        self.Bi5 = QtWidgets.QPushButton(self.centralwidget)
        self.Bi5.setGeometry(QtCore.QRect(650, 480, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bi5.setFont(font)
        self.Bi5.setObjectName("Bi5")
        self.Bd3 = QtWidgets.QPushButton(self.centralwidget)
        self.Bd3.setGeometry(QtCore.QRect(570, 280, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bd3.setFont(font)
        self.Bd3.setObjectName("Bd3")
        self.Bb6 = QtWidgets.QPushButton(self.centralwidget)
        self.Bb6.setGeometry(QtCore.QRect(690, 200, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bb6.setFont(font)
        self.Bb6.setObjectName("Bb6")
        self.Bd6 = QtWidgets.QPushButton(self.centralwidget)
        self.Bd6.setGeometry(QtCore.QRect(690, 280, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bd6.setFont(font)
        self.Bd6.setObjectName("Bd6")
        self.Bb5 = QtWidgets.QPushButton(self.centralwidget)
        self.Bb5.setGeometry(QtCore.QRect(650, 200, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bb5.setFont(font)
        self.Bb5.setObjectName("Bb5")
        self.Bi4 = QtWidgets.QPushButton(self.centralwidget)
        self.Bi4.setGeometry(QtCore.QRect(610, 480, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bi4.setFont(font)
        self.Bi4.setObjectName("Bi4")
        self.Ba7 = QtWidgets.QPushButton(self.centralwidget)
        self.Ba7.setGeometry(QtCore.QRect(730, 160, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Ba7.setFont(font)
        self.Ba7.setObjectName("Ba7")
        self.label_154 = QtWidgets.QLabel(self.centralwidget)
        self.label_154.setGeometry(QtCore.QRect(850, 560, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_154.setFont(font)
        self.label_154.setObjectName("label_154")
        self.Bh7 = QtWidgets.QPushButton(self.centralwidget)
        self.Bh7.setGeometry(QtCore.QRect(730, 440, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bh7.setFont(font)
        self.Bh7.setObjectName("Bh7")
        self.Bc1 = QtWidgets.QPushButton(self.centralwidget)
        self.Bc1.setGeometry(QtCore.QRect(490, 240, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bc1.setFont(font)
        self.Bc1.setObjectName("Bc1")
        self.Bj5 = QtWidgets.QPushButton(self.centralwidget)
        self.Bj5.setGeometry(QtCore.QRect(650, 520, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bj5.setFont(font)
        self.Bj5.setObjectName("Bj5")
        self.label_146 = QtWidgets.QLabel(self.centralwidget)
        self.label_146.setGeometry(QtCore.QRect(490, 560, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_146.setFont(font)
        self.label_146.setObjectName("label_146")
        self.label_221 = QtWidgets.QLabel(self.centralwidget)
        self.label_221.setGeometry(QtCore.QRect(460, 280, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_221.setFont(font)
        self.label_221.setObjectName("label_221")
        self.Bc6 = QtWidgets.QPushButton(self.centralwidget)
        self.Bc6.setGeometry(QtCore.QRect(690, 240, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bc6.setFont(font)
        self.Bc6.setObjectName("Bc6")
        self.Bb7 = QtWidgets.QPushButton(self.centralwidget)
        self.Bb7.setGeometry(QtCore.QRect(730, 200, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bb7.setFont(font)
        self.Bb7.setObjectName("Bb7")
        self.Bi9 = QtWidgets.QPushButton(self.centralwidget)
        self.Bi9.setGeometry(QtCore.QRect(810, 480, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bi9.setFont(font)
        self.Bi9.setObjectName("Bi9")
        self.Bf10 = QtWidgets.QPushButton(self.centralwidget)
        self.Bf10.setGeometry(QtCore.QRect(850, 360, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bf10.setFont(font)
        self.Bf10.setObjectName("Bf10")
        self.label_227 = QtWidgets.QLabel(self.centralwidget)
        self.label_227.setGeometry(QtCore.QRect(460, 520, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_227.setFont(font)
        self.label_227.setObjectName("label_227")
        self.Be7 = QtWidgets.QPushButton(self.centralwidget)
        self.Be7.setGeometry(QtCore.QRect(730, 320, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Be7.setFont(font)
        self.Be7.setObjectName("Be7")
        self.Bb10 = QtWidgets.QPushButton(self.centralwidget)
        self.Bb10.setGeometry(QtCore.QRect(850, 200, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bb10.setFont(font)
        self.Bb10.setObjectName("Bb10")
        self.label_207 = QtWidgets.QLabel(self.centralwidget)
        self.label_207.setGeometry(QtCore.QRect(690, 560, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_207.setFont(font)
        self.label_207.setObjectName("label_207")
        self.Bh9 = QtWidgets.QPushButton(self.centralwidget)
        self.Bh9.setGeometry(QtCore.QRect(810, 440, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bh9.setFont(font)
        self.Bh9.setObjectName("Bh9")
        self.Bg8 = QtWidgets.QPushButton(self.centralwidget)
        self.Bg8.setGeometry(QtCore.QRect(770, 400, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bg8.setFont(font)
        self.Bg8.setObjectName("Bg8")
        self.Bf1 = QtWidgets.QPushButton(self.centralwidget)
        self.Bf1.setGeometry(QtCore.QRect(490, 360, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bf1.setFont(font)
        self.Bf1.setObjectName("Bf1")
        self.Be1 = QtWidgets.QPushButton(self.centralwidget)
        self.Be1.setGeometry(QtCore.QRect(490, 320, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Be1.setFont(font)
        self.Be1.setObjectName("Be1")
        self.label_218 = QtWidgets.QLabel(self.centralwidget)
        self.label_218.setGeometry(QtCore.QRect(460, 240, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_218.setFont(font)
        self.label_218.setObjectName("label_218")
        self.Be4 = QtWidgets.QPushButton(self.centralwidget)
        self.Be4.setGeometry(QtCore.QRect(610, 320, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Be4.setFont(font)
        self.Be4.setObjectName("Be4")
        self.Bc7 = QtWidgets.QPushButton(self.centralwidget)
        self.Bc7.setGeometry(QtCore.QRect(730, 240, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bc7.setFont(font)
        self.Bc7.setObjectName("Bc7")
        self.Bg2 = QtWidgets.QPushButton(self.centralwidget)
        self.Bg2.setGeometry(QtCore.QRect(530, 400, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bg2.setFont(font)
        self.Bg2.setObjectName("Bg2")
        self.label_184 = QtWidgets.QLabel(self.centralwidget)
        self.label_184.setGeometry(QtCore.QRect(810, 560, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_184.setFont(font)
        self.label_184.setObjectName("label_184")
        self.Bd7 = QtWidgets.QPushButton(self.centralwidget)
        self.Bd7.setGeometry(QtCore.QRect(730, 280, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bd7.setFont(font)
        self.Bd7.setObjectName("Bd7")
        self.Ba3 = QtWidgets.QPushButton(self.centralwidget)
        self.Ba3.setGeometry(QtCore.QRect(570, 160, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Ba3.setFont(font)
        self.Ba3.setObjectName("Ba3")
        self.Ba6 = QtWidgets.QPushButton(self.centralwidget)
        self.Ba6.setGeometry(QtCore.QRect(690, 160, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Ba6.setFont(font)
        self.Ba6.setObjectName("Ba6")
        self.Bf9 = QtWidgets.QPushButton(self.centralwidget)
        self.Bf9.setGeometry(QtCore.QRect(810, 360, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bf9.setFont(font)
        self.Bf9.setObjectName("Bf9")
        self.Bb8 = QtWidgets.QPushButton(self.centralwidget)
        self.Bb8.setGeometry(QtCore.QRect(770, 200, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bb8.setFont(font)
        self.Bb8.setObjectName("Bb8")
        self.Bf5 = QtWidgets.QPushButton(self.centralwidget)
        self.Bf5.setGeometry(QtCore.QRect(650, 360, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bf5.setFont(font)
        self.Bf5.setObjectName("Bf5")
        self.Bc4 = QtWidgets.QPushButton(self.centralwidget)
        self.Bc4.setGeometry(QtCore.QRect(610, 240, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bc4.setFont(font)
        self.Bc4.setObjectName("Bc4")
        self.Bj8 = QtWidgets.QPushButton(self.centralwidget)
        self.Bj8.setGeometry(QtCore.QRect(770, 520, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bj8.setFont(font)
        self.Bj8.setObjectName("Bj8")
        self.Bb2 = QtWidgets.QPushButton(self.centralwidget)
        self.Bb2.setGeometry(QtCore.QRect(530, 200, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bb2.setFont(font)
        self.Bb2.setObjectName("Bb2")
        self.Ba9 = QtWidgets.QPushButton(self.centralwidget)
        self.Ba9.setGeometry(QtCore.QRect(810, 160, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Ba9.setFont(font)
        self.Ba9.setObjectName("Ba9")
        self.Bb4 = QtWidgets.QPushButton(self.centralwidget)
        self.Bb4.setGeometry(QtCore.QRect(610, 200, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bb4.setFont(font)
        self.Bb4.setObjectName("Bb4")
        self.Be6 = QtWidgets.QPushButton(self.centralwidget)
        self.Be6.setGeometry(QtCore.QRect(690, 320, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Be6.setFont(font)
        self.Be6.setObjectName("Be6")
        self.Bb9 = QtWidgets.QPushButton(self.centralwidget)
        self.Bb9.setGeometry(QtCore.QRect(810, 200, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bb9.setFont(font)
        self.Bb9.setObjectName("Bb9")
        self.Bd8 = QtWidgets.QPushButton(self.centralwidget)
        self.Bd8.setGeometry(QtCore.QRect(770, 280, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bd8.setFont(font)
        self.Bd8.setObjectName("Bd8")
        self.label_189 = QtWidgets.QLabel(self.centralwidget)
        self.label_189.setGeometry(QtCore.QRect(770, 560, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_189.setFont(font)
        self.label_189.setObjectName("label_189")
        self.label_130 = QtWidgets.QLabel(self.centralwidget)
        self.label_130.setGeometry(QtCore.QRect(530, 560, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_130.setFont(font)
        self.label_130.setObjectName("label_130")
        self.Bi2 = QtWidgets.QPushButton(self.centralwidget)
        self.Bi2.setGeometry(QtCore.QRect(530, 480, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bi2.setFont(font)
        self.Bi2.setObjectName("Bi2")
        self.Bg6 = QtWidgets.QPushButton(self.centralwidget)
        self.Bg6.setGeometry(QtCore.QRect(690, 400, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bg6.setFont(font)
        self.Bg6.setObjectName("Bg6")
        self.Bg10 = QtWidgets.QPushButton(self.centralwidget)
        self.Bg10.setGeometry(QtCore.QRect(850, 400, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bg10.setFont(font)
        self.Bg10.setObjectName("Bg10")
        self.Bj1 = QtWidgets.QPushButton(self.centralwidget)
        self.Bj1.setGeometry(QtCore.QRect(490, 520, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bj1.setFont(font)
        self.Bj1.setObjectName("Bj1")
        self.Bd2 = QtWidgets.QPushButton(self.centralwidget)
        self.Bd2.setGeometry(QtCore.QRect(530, 280, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bd2.setFont(font)
        self.Bd2.setObjectName("Bd2")
        self.label_222 = QtWidgets.QLabel(self.centralwidget)
        self.label_222.setGeometry(QtCore.QRect(460, 440, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_222.setFont(font)
        self.label_222.setObjectName("label_222")
        self.Ba5 = QtWidgets.QPushButton(self.centralwidget)
        self.Ba5.setGeometry(QtCore.QRect(650, 160, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Ba5.setFont(font)
        self.Ba5.setObjectName("Ba5")
        self.Bf2 = QtWidgets.QPushButton(self.centralwidget)
        self.Bf2.setGeometry(QtCore.QRect(530, 360, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bf2.setFont(font)
        self.Bf2.setObjectName("Bf2")
        self.Bh10 = QtWidgets.QPushButton(self.centralwidget)
        self.Bh10.setGeometry(QtCore.QRect(850, 440, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bh10.setFont(font)
        self.Bh10.setObjectName("Bh10")
        self.Bi8 = QtWidgets.QPushButton(self.centralwidget)
        self.Bi8.setGeometry(QtCore.QRect(770, 480, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bi8.setFont(font)
        self.Bi8.setObjectName("Bi8")
        self.Bg5 = QtWidgets.QPushButton(self.centralwidget)
        self.Bg5.setGeometry(QtCore.QRect(650, 400, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bg5.setFont(font)
        self.Bg5.setObjectName("Bg5")
        self.Bi6 = QtWidgets.QPushButton(self.centralwidget)
        self.Bi6.setGeometry(QtCore.QRect(690, 480, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bi6.setFont(font)
        self.Bi6.setObjectName("Bi6")
        self.Bc5 = QtWidgets.QPushButton(self.centralwidget)
        self.Bc5.setGeometry(QtCore.QRect(650, 240, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bc5.setFont(font)
        self.Bc5.setObjectName("Bc5")
        self.label_211 = QtWidgets.QLabel(self.centralwidget)
        self.label_211.setGeometry(QtCore.QRect(730, 560, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_211.setFont(font)
        self.label_211.setObjectName("label_211")
        self.Bd5 = QtWidgets.QPushButton(self.centralwidget)
        self.Bd5.setGeometry(QtCore.QRect(650, 280, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bd5.setFont(font)
        self.Bd5.setObjectName("Bd5")
        self.Be3 = QtWidgets.QPushButton(self.centralwidget)
        self.Be3.setGeometry(QtCore.QRect(570, 320, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Be3.setFont(font)
        self.Be3.setObjectName("Be3")
        self.Bh6 = QtWidgets.QPushButton(self.centralwidget)
        self.Bh6.setGeometry(QtCore.QRect(690, 440, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bh6.setFont(font)
        self.Bh6.setObjectName("Bh6")
        self.Bc9 = QtWidgets.QPushButton(self.centralwidget)
        self.Bc9.setGeometry(QtCore.QRect(810, 240, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bc9.setFont(font)
        self.Bc9.setObjectName("Bc9")
        self.Bf7 = QtWidgets.QPushButton(self.centralwidget)
        self.Bf7.setGeometry(QtCore.QRect(730, 360, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bf7.setFont(font)
        self.Bf7.setObjectName("Bf7")
        self.Bd4 = QtWidgets.QPushButton(self.centralwidget)
        self.Bd4.setGeometry(QtCore.QRect(610, 280, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bd4.setFont(font)
        self.Bd4.setObjectName("Bd4")
        self.Bi3 = QtWidgets.QPushButton(self.centralwidget)
        self.Bi3.setGeometry(QtCore.QRect(570, 480, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bi3.setFont(font)
        self.Bi3.setObjectName("Bi3")
        self.Ba10 = QtWidgets.QPushButton(self.centralwidget)
        self.Ba10.setGeometry(QtCore.QRect(850, 160, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Ba10.setFont(font)
        self.Ba10.setObjectName("Ba10")
        self.label_157 = QtWidgets.QLabel(self.centralwidget)
        self.label_157.setGeometry(QtCore.QRect(570, 560, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_157.setFont(font)
        self.label_157.setObjectName("label_157")
        self.Bh1 = QtWidgets.QPushButton(self.centralwidget)
        self.Bh1.setGeometry(QtCore.QRect(490, 440, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bh1.setFont(font)
        self.Bh1.setObjectName("Bh1")
        self.Bg7 = QtWidgets.QPushButton(self.centralwidget)
        self.Bg7.setGeometry(QtCore.QRect(730, 400, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bg7.setFont(font)
        self.Bg7.setObjectName("Bg7")
        self.Be9 = QtWidgets.QPushButton(self.centralwidget)
        self.Be9.setGeometry(QtCore.QRect(810, 320, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Be9.setFont(font)
        self.Be9.setObjectName("Be9")
        self.Bf8 = QtWidgets.QPushButton(self.centralwidget)
        self.Bf8.setGeometry(QtCore.QRect(770, 360, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bf8.setFont(font)
        self.Bf8.setObjectName("Bf8")
        self.Bg9 = QtWidgets.QPushButton(self.centralwidget)
        self.Bg9.setGeometry(QtCore.QRect(810, 400, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bg9.setFont(font)
        self.Bg9.setObjectName("Bg9")
        self.Bh5 = QtWidgets.QPushButton(self.centralwidget)
        self.Bh5.setGeometry(QtCore.QRect(650, 440, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bh5.setFont(font)
        self.Bh5.setObjectName("Bh5")
        self.Be2 = QtWidgets.QPushButton(self.centralwidget)
        self.Be2.setGeometry(QtCore.QRect(530, 320, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Be2.setFont(font)
        self.Be2.setObjectName("Be2")
        self.Bf3 = QtWidgets.QPushButton(self.centralwidget)
        self.Bf3.setGeometry(QtCore.QRect(570, 360, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bf3.setFont(font)
        self.Bf3.setObjectName("Bf3")
        self.Bc2 = QtWidgets.QPushButton(self.centralwidget)
        self.Bc2.setGeometry(QtCore.QRect(530, 240, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bc2.setFont(font)
        self.Bc2.setObjectName("Bc2")
        self.Ba1 = QtWidgets.QPushButton(self.centralwidget)
        self.Ba1.setGeometry(QtCore.QRect(490, 160, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Ba1.setFont(font)
        self.Ba1.setObjectName("Ba1")
        self.Be5 = QtWidgets.QPushButton(self.centralwidget)
        self.Be5.setGeometry(QtCore.QRect(650, 320, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Be5.setFont(font)
        self.Be5.setObjectName("Be5")
        self.Bj9 = QtWidgets.QPushButton(self.centralwidget)
        self.Bj9.setGeometry(QtCore.QRect(810, 520, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bj9.setFont(font)
        self.Bj9.setObjectName("Bj9")
        self.Bf6 = QtWidgets.QPushButton(self.centralwidget)
        self.Bf6.setGeometry(QtCore.QRect(690, 360, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bf6.setFont(font)
        self.Bf6.setObjectName("Bf6")
        self.Ba8 = QtWidgets.QPushButton(self.centralwidget)
        self.Ba8.setGeometry(QtCore.QRect(770, 160, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Ba8.setFont(font)
        self.Ba8.setObjectName("Ba8")
        self.Bj6 = QtWidgets.QPushButton(self.centralwidget)
        self.Bj6.setGeometry(QtCore.QRect(690, 520, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bj6.setFont(font)
        self.Bj6.setObjectName("Bj6")
        self.Bc10 = QtWidgets.QPushButton(self.centralwidget)
        self.Bc10.setGeometry(QtCore.QRect(850, 240, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bc10.setFont(font)
        self.Bc10.setObjectName("Bc10")
        self.Bi10 = QtWidgets.QPushButton(self.centralwidget)
        self.Bi10.setGeometry(QtCore.QRect(850, 480, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bi10.setFont(font)
        self.Bi10.setObjectName("Bi10")
        self.Be10 = QtWidgets.QPushButton(self.centralwidget)
        self.Be10.setGeometry(QtCore.QRect(850, 320, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Be10.setFont(font)
        self.Be10.setObjectName("Be10")
        self.label_202 = QtWidgets.QLabel(self.centralwidget)
        self.label_202.setGeometry(QtCore.QRect(460, 320, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_202.setFont(font)
        self.label_202.setObjectName("label_202")
        self.Ba4 = QtWidgets.QPushButton(self.centralwidget)
        self.Ba4.setGeometry(QtCore.QRect(610, 160, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Ba4.setFont(font)
        self.Ba4.setObjectName("Ba4")
        self.Bh3 = QtWidgets.QPushButton(self.centralwidget)
        self.Bh3.setGeometry(QtCore.QRect(570, 440, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bh3.setFont(font)
        self.Bh3.setObjectName("Bh3")
        self.Bh4 = QtWidgets.QPushButton(self.centralwidget)
        self.Bh4.setGeometry(QtCore.QRect(610, 440, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bh4.setFont(font)
        self.Bh4.setObjectName("Bh4")
        self.label_193 = QtWidgets.QLabel(self.centralwidget)
        self.label_193.setGeometry(QtCore.QRect(460, 400, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_193.setFont(font)
        self.label_193.setObjectName("label_193")
        self.Bj2 = QtWidgets.QPushButton(self.centralwidget)
        self.Bj2.setGeometry(QtCore.QRect(530, 520, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bj2.setFont(font)
        self.Bj2.setObjectName("Bj2")
        self.Bh2 = QtWidgets.QPushButton(self.centralwidget)
        self.Bh2.setGeometry(QtCore.QRect(530, 440, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bh2.setFont(font)
        self.Bh2.setObjectName("Bh2")
        self.Bj10 = QtWidgets.QPushButton(self.centralwidget)
        self.Bj10.setGeometry(QtCore.QRect(850, 520, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bj10.setFont(font)
        self.Bj10.setObjectName("Bj10")
        self.label_203 = QtWidgets.QLabel(self.centralwidget)
        self.label_203.setGeometry(QtCore.QRect(460, 480, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_203.setFont(font)
        self.label_203.setObjectName("label_203")
        self.label_217 = QtWidgets.QLabel(self.centralwidget)
        self.label_217.setGeometry(QtCore.QRect(460, 160, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_217.setFont(font)
        self.label_217.setObjectName("label_217")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(460, 200, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.Ba2 = QtWidgets.QPushButton(self.centralwidget)
        self.Ba2.setGeometry(QtCore.QRect(530, 160, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Ba2.setFont(font)
        self.Ba2.setObjectName("Ba2")
        self.Bi1 = QtWidgets.QPushButton(self.centralwidget)
        self.Bi1.setGeometry(QtCore.QRect(490, 480, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bi1.setFont(font)
        self.Bi1.setObjectName("Bi1")
        self.Bc3 = QtWidgets.QPushButton(self.centralwidget)
        self.Bc3.setGeometry(QtCore.QRect(570, 240, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Bc3.setFont(font)
        self.Bc3.setObjectName("Bc3")
        self.super_label = QtWidgets.QLabel(self.centralwidget)
        self.super_label.setGeometry(QtCore.QRect(470, 80, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.super_label.setFont(font)
        self.super_label.setObjectName("super_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1361, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Продолжить"))
        self.Bi7.setText(_translate("MainWindow", "-"))
        self.Bd1.setText(_translate("MainWindow", "-"))
        self.Bd10.setText(_translate("MainWindow", "-"))
        self.label_127.setText(_translate("MainWindow", "  4"))
        self.Bg4.setText(_translate("MainWindow", "-"))
        self.Bj4.setText(_translate("MainWindow", "-"))
        self.Bj7.setText(_translate("MainWindow", "-"))
        self.label_149.setText(_translate("MainWindow", "f"))
        self.Be8.setText(_translate("MainWindow", "-"))
        self.Bd9.setText(_translate("MainWindow", "-"))
        self.label_230.setText(_translate("MainWindow", "  5"))
        self.Bj3.setText(_translate("MainWindow", "-"))
        self.Bc8.setText(_translate("MainWindow", "-"))
        self.Bb3.setText(_translate("MainWindow", "-"))
        self.Bg1.setText(_translate("MainWindow", "-"))
        self.Bh8.setText(_translate("MainWindow", "-"))
        self.Bb1.setText(_translate("MainWindow", "-"))
        self.Bg3.setText(_translate("MainWindow", "-"))
        self.Bf4.setText(_translate("MainWindow", "-"))
        self.Bi5.setText(_translate("MainWindow", "-"))
        self.Bd3.setText(_translate("MainWindow", "-"))
        self.Bb6.setText(_translate("MainWindow", "-"))
        self.Bd6.setText(_translate("MainWindow", "-"))
        self.Bb5.setText(_translate("MainWindow", "-"))
        self.Bi4.setText(_translate("MainWindow", "-"))
        self.Ba7.setText(_translate("MainWindow", "-"))
        self.label_154.setText(_translate("MainWindow", " 10"))
        self.Bh7.setText(_translate("MainWindow", "-"))
        self.Bc1.setText(_translate("MainWindow", "-"))
        self.Bj5.setText(_translate("MainWindow", "-"))
        self.label_146.setText(_translate("MainWindow", "  1"))
        self.label_221.setText(_translate("MainWindow", "d"))
        self.Bc6.setText(_translate("MainWindow", "-"))
        self.Bb7.setText(_translate("MainWindow", "-"))
        self.Bi9.setText(_translate("MainWindow", "-"))
        self.Bf10.setText(_translate("MainWindow", "-"))
        self.label_227.setText(_translate("MainWindow", "j"))
        self.Be7.setText(_translate("MainWindow", "-"))
        self.Bb10.setText(_translate("MainWindow", "-"))
        self.label_207.setText(_translate("MainWindow", "  6"))
        self.Bh9.setText(_translate("MainWindow", "-"))
        self.Bg8.setText(_translate("MainWindow", "-"))
        self.Bf1.setText(_translate("MainWindow", "-"))
        self.Be1.setText(_translate("MainWindow", "-"))
        self.label_218.setText(_translate("MainWindow", "c"))
        self.Be4.setText(_translate("MainWindow", "-"))
        self.Bc7.setText(_translate("MainWindow", "-"))
        self.Bg2.setText(_translate("MainWindow", "-"))
        self.label_184.setText(_translate("MainWindow", "  9"))
        self.Bd7.setText(_translate("MainWindow", "-"))
        self.Ba3.setText(_translate("MainWindow", "-"))
        self.Ba6.setText(_translate("MainWindow", "-"))
        self.Bf9.setText(_translate("MainWindow", "-"))
        self.Bb8.setText(_translate("MainWindow", "-"))
        self.Bf5.setText(_translate("MainWindow", "-"))
        self.Bc4.setText(_translate("MainWindow", "-"))
        self.Bj8.setText(_translate("MainWindow", "-"))
        self.Bb2.setText(_translate("MainWindow", "-"))
        self.Ba9.setText(_translate("MainWindow", "-"))
        self.Bb4.setText(_translate("MainWindow", "-"))
        self.Be6.setText(_translate("MainWindow", "-"))
        self.Bb9.setText(_translate("MainWindow", "-"))
        self.Bd8.setText(_translate("MainWindow", "-"))
        self.label_189.setText(_translate("MainWindow", "  8"))
        self.label_130.setText(_translate("MainWindow", "  2"))
        self.Bi2.setText(_translate("MainWindow", "-"))
        self.Bg6.setText(_translate("MainWindow", "-"))
        self.Bg10.setText(_translate("MainWindow", "-"))
        self.Bj1.setText(_translate("MainWindow", "-"))
        self.Bd2.setText(_translate("MainWindow", "-"))
        self.label_222.setText(_translate("MainWindow", "h"))
        self.Ba5.setText(_translate("MainWindow", "-"))
        self.Bf2.setText(_translate("MainWindow", "-"))
        self.Bh10.setText(_translate("MainWindow", "-"))
        self.Bi8.setText(_translate("MainWindow", "-"))
        self.Bg5.setText(_translate("MainWindow", "-"))
        self.Bi6.setText(_translate("MainWindow", "-"))
        self.Bc5.setText(_translate("MainWindow", "-"))
        self.label_211.setText(_translate("MainWindow", "  7"))
        self.Bd5.setText(_translate("MainWindow", "-"))
        self.Be3.setText(_translate("MainWindow", "-"))
        self.Bh6.setText(_translate("MainWindow", "-"))
        self.Bc9.setText(_translate("MainWindow", "-"))
        self.Bf7.setText(_translate("MainWindow", "-"))
        self.Bd4.setText(_translate("MainWindow", "-"))
        self.Bi3.setText(_translate("MainWindow", "-"))
        self.Ba10.setText(_translate("MainWindow", "-"))
        self.label_157.setText(_translate("MainWindow", "  3"))
        self.Bh1.setText(_translate("MainWindow", "-"))
        self.Bg7.setText(_translate("MainWindow", "-"))
        self.Be9.setText(_translate("MainWindow", "-"))
        self.Bf8.setText(_translate("MainWindow", "-"))
        self.Bg9.setText(_translate("MainWindow", "-"))
        self.Bh5.setText(_translate("MainWindow", "-"))
        self.Be2.setText(_translate("MainWindow", "-"))
        self.Bf3.setText(_translate("MainWindow", "-"))
        self.Bc2.setText(_translate("MainWindow", "-"))
        self.Ba1.setText(_translate("MainWindow", "-"))
        self.Be5.setText(_translate("MainWindow", "-"))
        self.Bj9.setText(_translate("MainWindow", "-"))
        self.Bf6.setText(_translate("MainWindow", "-"))
        self.Ba8.setText(_translate("MainWindow", "-"))
        self.Bj6.setText(_translate("MainWindow", "-"))
        self.Bc10.setText(_translate("MainWindow", "-"))
        self.Bi10.setText(_translate("MainWindow", "-"))
        self.Be10.setText(_translate("MainWindow", "-"))
        self.label_202.setText(_translate("MainWindow", "e"))
        self.Ba4.setText(_translate("MainWindow", "-"))
        self.Bh3.setText(_translate("MainWindow", "-"))
        self.Bh4.setText(_translate("MainWindow", "-"))
        self.label_193.setText(_translate("MainWindow", "g"))
        self.Bj2.setText(_translate("MainWindow", "-"))
        self.Bh2.setText(_translate("MainWindow", "-"))
        self.Bj10.setText(_translate("MainWindow", "-"))
        self.label_203.setText(_translate("MainWindow", "i"))
        self.label_217.setText(_translate("MainWindow", "a"))
        self.label_13.setText(_translate("MainWindow", "b"))
        self.Ba2.setText(_translate("MainWindow", "-"))
        self.Bi1.setText(_translate("MainWindow", "-"))
        self.Bc3.setText(_translate("MainWindow", "-"))
        self.super_label.setText(_translate("MainWindow", "Расставьте четырёхпалубный корабль:"))

